#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
configs:
  nginx.conf:
    file: /run/configs/etc/nginx/nginx.conf
secrets:
  default.conf:
    file: /run/secrets/etc/nginx/conf.d/default.conf
services:
  nginx:
    configs:
    - mode: 0400
      source: nginx.conf
      target: /etc/nginx/nginx.conf
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
        reservations:
          cpus: "0.1"
          memory: 100M
    expose:
    - "8080"
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 30s
      test: curl -f localhost:8080
      timeout: 1s
    image: academiaonline/nginx:latest
    ports:
    - "80:8080"
    secrets:
    - mode: 0400
      source: default.conf
      target: /etc/nginx/conf.d/default.conf
    volumes:
    - nginx-cache-vol:/var/cache/nginx
    - nginx-run-vol:/var/run
version: "3.8"
volumes:
  nginx-cache-vol:
  nginx-run-vol:
#########################################################################
